### ISSUE TITLE
Is it possible to use this model without ECMWF MARS access?

### ISSUE THREAD

**Issue by ThomasMGeo** [ecmwf-lab/ai-models-fourcastnetv2#1]
When I try to download the assets (specifically surface fields), it requests MARS access. 

Wondering if it's possible to download the assets without this access?

**Comment by ThomasMGeo** [comment]
The below is output from this: `!ai-models --download-assets --assets ~/share/ai-models-assets --assets-sub-directory fourcastnetv2-small`

```
2024-11-25 17:51:50,291 INFO Writing results to fourcastnetv2-small.grib
2024-11-25 17:51:50,301 INFO Downloading /share/ai-models-assets/fourcastnetv2-small/weights.tar
2024-11-25 17:51:50,302 INFO Downloading https://get.ecmwf.int/repository/test-data/ai-models/fourcastnetv2/small/weights.tar
2024-11-25 17:56:56,557 INFO Downloading /share/ai-models-assets/fourcastnetv2-small/global_means.npy
2024-11-25 17:56:56,557 INFO Downloading https://get.ecmwf.int/repository/test-data/ai-models/fourcastnetv2/small/global_means.npy
2024-11-25 17:56:57,760 INFO Downloading /share/ai-models-assets/fourcastnetv2-small/global_stds.npy
2024-11-25 17:56:57,760 INFO Downloading https://get.ecmwf.int/repository/test-data/ai-models/fourcastnetv2/small/global_stds.npy
2024-11-25 17:56:58,486 INFO Loading /home/jovyan/share/ai-models-assets/fourcastnetv2-small/global_means.npy
2024-11-25 17:56:58,487 INFO Loading /home/jovyan/share/ai-models-assets/fourcastnetv2-small/global_stds.npy
2024-11-25 17:56:58,488 INFO Loading surface fields from MARS
2024-11-25 17:56:58 ECMWF API python library 1.6.3
2024-11-25 17:56:58 ECMWF API at https://api.ecmwf.int/v1
2024-11-25 17:56:59 Welcome Thomas Martin
2024-11-25 17:57:00,379 INFO Total time: 5 minutes 11 seconds.
Traceback (most recent call last):
  File "/opt/conda/envs/tm-fall-2024/bin/ai-models", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/__main__.py", line 362, in main
    _main(sys.argv[1:])
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/__main__.py", line 310, in _main
    run(vars(args), unknownargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/__main__.py", line 335, in run
    model.run()
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models_fourcastnetv2/model.py", line 186, in run
    all_fields = self.all_fields
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/model.py", line 116, in all_fields
    return self.input.all_fields
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/inputs/base.py", line 100, in all_fields
    return self.fields_sfc + self.fields_pl + self.fields_ml
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/inputs/base.py", line 35, in fields_sfc
    [
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/inputs/base.py", line 36, in <listcomp>
    self.sfc_load_source(
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ai_models/inputs/mars.py", line 31, in sfc_load_source
    return ekd.from_source("mars", kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/__init__.py", line 150, in from_source
    src = get_source(name, *args, **kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/__init__.py", line 131, in __call__
    source = klass(*args, **kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/core/__init__.py", line 22, in __call__
    obj.__init__(*args, **kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/ecmwf_api.py", line 72, in __init__
    self.path = [self._retrieve(r) for r in requests]
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/ecmwf_api.py", line 72, in <listcomp>
    self.path = [self._retrieve(r) for r in requests]
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/ecmwf_api.py", line 86, in _retrieve
    return self.cache_file(
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/__init__.py", line 68, in cache_file
    return cache_file(owner, create, args, **kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/core/caching.py", line 1022, in cache_file
    owner_data = create(path + ".tmp", args)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/earthkit/data/sources/ecmwf_api.py", line 84, in retrieve
    self.service().execute(request, target)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ecmwfapi/api.py", line 633, in execute
    c = APIRequest(
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ecmwfapi/api.py", line 455, in __init__
    service_specific_info = self.connection.call(
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ecmwfapi/api.py", line 183, in wrapped
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/tm-fall-2024/lib/python3.10/site-packages/ecmwfapi/api.py", line 386, in call
    raise APIException("ecmwf.API error 1: %s" % (self.last["error"],))
ecmwfapi.api.APIException: "ecmwf.API error 1: User 'tmartin@ucar.edu' has no access to services/mars"
```
